auto: false
server: false
lsi: false
markdown: rdiscount
pygments: true
permalink: /:title
category_dir: topics
category_title_prefix:
exclude: ["lib", "Capfile", "config", "log", "Rakefile", "tmp"]
destination: public

